import { IsBoolean, IsNumber, IsString } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";

export class PostAmbassadorReferralDto {
  @IsNumber()
  @ApiProperty({ description: "Revenue generated by the referral" })
  revenue: number;

  @IsString()
  @ApiProperty({ description: "Unique transaction identifier" })
  transaction_uid: string;

  @IsString()
  @ApiProperty({ description: "First name of the client" })
  first_name: string;

  @IsString()
  @ApiProperty({ description: "Email address of the client" })
  email: string;

  @IsNumber()
  @ApiProperty({ description: "Campaign unique identifier" })
  campaign_uid: number;

  @IsString()
  @ApiProperty({ description: "Short code for the referral" })
  short_code: string;

  @IsBoolean()
  @ApiProperty({ description: "Referral Approved", default: true })
  is_approved: Boolean = true;
}
