require("dotenv").config();
export const PG_DATA_SOURCE = "PG_DATA_SOURCE";
export const REFERRAL_REPOSITORY = "REFERRAL_REPOSITORY";
export const CAMPAIGN_REPOSITORY = "CAMPAIGN_REPOSITORY";
export const TENANT_REPOSITORY = "TENANT_REPOSITORY";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const USER_ROLE_REPOSITORY = "USER_ROLE_REPOSITORY";
export const USER_HOTEL_REPOSITORY = "USER_HOTEL_REPOSITORY";
export const USER_MERCHANT_REPOSITORY = "USER_MERCHANT_REPOSITORY";
export const ROLE_REPOSITORY = "ROLE_REPOSITORY";
export const ROLE_HOTEL_REPOSITORY = "ROLE_HOTEL_REPOSITORY";
export const ROLE_MERCHANT_REPOSITORY = "ROLE_MERCHANT_REPOSITORY";
export const ROLE_PERMISSION_REPOSITORY = "ROLE_PERMISSION_REPOSITORY";
export const CITY_REPOSITORY = "CITY_REPOSITORY";
export const HOTEL_REPOSITORY = "HOTEL_REPOSITORY";
export const MEAL_PERIOD_REPOSITORY = "MEAL_PERIOD_REPOSITORY";
export const MERCHANT_REPOSITORY = "MERCHANT_REPOSITORY";
export const MERCHANT_HOTEL_REPOSITORY = "MERCHANT_HOTEL_REPOSITORY";
export const PERMISSION_REPOSITORY = "PERMISSION_REPOSITORY";
export const CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY";
export const MODIFIER_REPOSITORY = "MODIFIER_REPOSITORY";
export const MODIFIER_OPTION_REPOSITORY = "MODIFIER_OPTION_REPOSITORY";
export const ITEM_REPOSITORY = "ITEM_REPOSITORY";
export const ITEM_CATEGORY_REPOSITORY = "ITEM_CATEGORY_REPOSITORY";
export const ITEM_MODIFIER_REPOSITORY = "ITEM_MODIFIER_REPOSITORY";
export const MENU_REPOSITORY = "MENU_REPOSITORY";
export const MENU_CATEGORY_REPOSITORY = "MENU_CATEGORY_REPOSITORY";
export const MENU_ITEM_REPOSITORY = "MENU_ITEM_REPOSITORY";
export const MENU_HOTEL_REPOSITORY = "MENU_HOTEL_REPOSITORY";
export const VOUCHER_PROGRAM_REPOSITORY = "VOUCHER_PROGRAM_REPOSITORY";
export const VOUCHER_CODE_REPOSITORY = "VOUCHER_CODE_REPOSITORY";
export const VOUCHER_PROGRAM_HOTEL_REPOSITORY =
  "VOUCHER_PROGRAM_HOTEL_REPOSITORY";
export const VOUCHER_PROGRAM_RULE_REPOSITORY =
  "VOUCHER_PROGRAM_RULE_REPOSITORY";
export const DISCOUNT_CODE_REPOSITORY = "DISCOUNT_CODE_REPOSITORY";

export const ORDER_REPOSITORY = "ORDER_REPOSITORY";
export const ORDER_ITEM_REPOSITORY = "ORDER_ITEM_REPOSITORY";
export const ORDER_ITEM_MODIFIER_REPOSITORY = "ORDER_ITEM_MODIFIER_REPOSITORY";
export const ORDER_ITEM_MODIFIER_OPTIONS_REPOSITORY =
  "ORDER_ITEM_MODIFIER_OPTIONS_REPOSITORY";
export const ORDER_STATUS_REPOSITORY = "ORDER_STATUS_REPOSITORY";
export const ORDER_CALCULATION_REPOSITORY = "ORDER_CALCULATION_REPOSITORY";
export const OUT_OF_STOCK_REPOSITORY = "OUT_OF_STOCK_REPOSITORY";
export const PAYMENT_LOG_REPOSITORY = "PAYMENT_LOG_REPOSITORY";
export const GUEST_REPOSITORY = "GUEST_REPOSITORY";
export const HOTEL_ARRIVALS_REPOSITORY = "HOTEL_ARRIVALS_REPOSITORY";
export const CONVERSATIONS_REPOSITORY = "CONVERSATIONS_REPOSITORY";

export const PAYMENT_INTENT_SUCCEEDED = "payment_intent.succeeded";
export const STRIPE_DEFAULT_SYSTEM_CURRENCY = "usd";
export const STRIPE_PAYMENT_INTENT_AMOUNT_CAPTURABLE_UPDATED =
  "payment_intent.amount_capturable_updated";
export const STRIPE_PAYMENT_INTENT_CANCELED = "payment_intent.canceled";
export const STRIPE_PAYMENT_INTENT_CREATED = "payment_intent.created";
export const STRIPE_PAYMENT_INTENT_PARTIALLY_FUNDED =
  "payment_intent.partially_funded";
export const STRIPE_PAYMENT_INTENT_FAILED = "payment_intent.payment_failed";
export const STRIPE_PAYMENT_INTENT_PROCESSING = "payment_intent.processing";
export const STRIPE_PAYMENT_INTENT_REQUIRES_ACTION =
  "payment_intent.requires_action";
export const STRIPE_PAYMENT_INTENT_SUCCEEDED = "payment_intent.succeeded";
export const STRIPE_REFUND_CREATED = "refund.created";
export const STRIPE_REFUND_UPDATED = "refund.updated";

export const AWS_DEFAULT_REGION = "us-east-1";
export const AWS_ACCESS_KEY = process.env.ACCESS_KEY_ID;
export const AWS_SECRET_ACCESS_KEY = process.env.SECRET_ACCESS_KEY;

export const DB_TYPE = "postgres";
export const DB_HOST = process.env.DB_HOST;
export const DB_PORT = process.env.DB_PORT;
export const DB_USERNAME = process.env.DB_USERNAME;
export const DB_PASSWORD = process.env.DB_PASSWORD;
export const DB_DATABASE = process.env.DB_DATABASE;

export const CONCIERGE_BULK_SQS_QUEUE_URL =
  process.env.CONCIERGE_BULK_SQS_QUEUE_URL;
