FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y coreutils
RUN apt-get -y install curl
RUN apt-get install -y vim
# RUN apt-get install -y ca-certificates
# RUN apt-get -y install gcc

RUN apt-get -y install nodejs
RUN apt-get -y install npm

ENTRYPOINT ["tail", "-f", "/dev/null"]